### PR TITLE
Change transtition by using navigation replace action.

### PR DESCRIPTION
**Pull request by jpuerto**
Fix issue #4

### CODE REVIEW

**Comment by esarbanis** [comment]
Hi @jpuerto, thank you for this PR!

May I ask you to add a test case to better illustrate the problem at hand? Use can use the example you mentioned in the issue with a push, replace and pop.

**Comment by esarbanis** [comment]
@jpuerto can you please resolve the conflicts and add a simple test, so that we move forward with this?

Thanks 🙏

**Comment by jpuerto** [comment]
Hi @esarbanis 
Done, I've updated the test cases and fix also the code to allow null values as previousPath.

**Comment by esarbanis** [comment]
Hi @jpuerto thanks for sticking to this 🙂.

Can you please squash your commits into 1 and rebase from master? There are still some conflicts in this PR.

**Comment by jpuerto** [comment]
Hi @esarbanis , I have fixed the PR.

**Comment by jpuerto** [comment]
This PR is not ready for the new action "pushNamedAndRemoveUntil" as I should keep the stack of pages so I have created a middleware to keep track of the navigation stack.

**Pull request closed without merging**
