### PR TITLE
Support popUntil action

### PR DESCRIPTION
**Pull request by shaxxx**
I believe this is straightforward enough.

Regards.

### CODE REVIEW

**Comment by shaxxx** [comment]
Seems like CI is broken? Can you provide a feedback on this?

**Comment by esarbanis** [comment]
Hi @shaxxx and thank you for this PR!

I have fixed the pipeline issue in master, so make sure to rebase on top of it again. 

Please use `flutter format` to format your code. It makes it easier to review and maintains its consistency.

Can you please add the appropriate test cases, so that we maintain our code coverage?

**Comment by lukevenediger** [comment]
I've re-implemented this in pull request #14.

**Comment by shaxxx** [comment]
Great, I'll take a look at it asap. 
I'm sorry I didn't have time to update PR, I was busy and then just forgot about it once I shipped the code.

**Pull request closed without merging**
